SAR-7838 Create new create journey for Ltd Company
hmrc/incorporated-entity-identification-frontend pull request #121
Opened 2021-07-05 13:50 UTC by EviNikolaidou

2021-07-08 09:22 UTC, r-melvin commented on README.md
> -### POST /journey
this should have the `/`

2021-07-08 09:23 UTC, r-melvin commented on app/uk/gov/hmrc/incorporatedentityidentificationfrontend/api/controllers/JourneyController.scala
> +  def createLtdCompanyJourney: Action[JourneyConfig] = createJourney(LtdCompany)
These two APIs aren't for different entities, they're both limited companies

2021-07-08 09:23 UTC, r-melvin commented on app/uk/gov/hmrc/incorporatedentityidentificationfrontend/repositories/JourneyConfigRepository.scala
> +//    }
This can be deleted

2021-07-09 06:02 UTC, kabuumu requested changes

2021-07-09 06:02 UTC, kabuumu commented on conf/api.routes
> +POST        /journey        uk.gov.hmrc.incorporatedentityidentificationfrontend.api.controllers.JourneyController.createLtdCompanyJourney()
Was part of this ticket to create a new limited company specific route?

2021-07-12 09:35 UTC, HarrNM approved these changes

2021-07-12 09:35 UTC, merged