SAR-8762 Update Submission logic in CheckYourAnswers controller
hmrc/incorporated-entity-identification-frontend pull request #142
Opened 2021-12-07 10:49 UTC by EviNikolaidou

2021-12-08 10:14 UTC, kabuumu requested changes
Has this been tested manually? I think that it might not end up registering because the CheckYourAnswers controller will hand back to the calling service before it can register.

2021-12-08 10:14 UTC, kabuumu commented on it/uk/gov/hmrc/incorporatedentityidentificationfrontend/controllers/CheckYourAnswersControllerISpec.scala
> +      }
This should register, if it hands back to the calling service then no registration will have happened.

2021-12-15 09:15 UTC, HarrNM commented on it/uk/gov/hmrc/incorporatedentityidentificationfrontend/controllers/CheckYourAnswersControllerISpec.scala
> +      "return a redirect to continueUrl" when {
This isn't redirecting to the continueUrl, please can we rename it

2021-12-15 09:49 UTC, HarrNM approved these changes

2021-12-15 15:53 UTC, merged