SAR-9480 Update identifier match storage and audit values
hmrc/incorporated-entity-identification-frontend pull request #170
Opened 2022-04-25 15:46 UTC by woollett-r

2022-04-26 16:03 UTC, robertom-binqua requested changes

2022-04-26 16:04 UTC, robertom-binqua commented
Richard are not compulsory things ... if you agree do it otherwise I am going to approve it.
Let me know

2022-04-27 08:50 UTC, woollett-r commented on app/uk/gov/hmrc/incorporatedentityidentificationfrontend/models/IncorporatedEntityInformation.scala
> +        identifiersMatchKey -> incorporatedEntityInformation.identifiersMatch.toString,
Actually, I think it is the other way around. The "writes" method should serialise an instance of IncorporatedEntityInformation" and, therefore, should output a string corresponding to the appropriate validation response (or match).

2022-04-27 08:52 UTC, woollett-r commented on app/uk/gov/hmrc/incorporatedentityidentificationfrontend/models/IncorporatedEntityInformation.scala
> +        Json.obj(IdentifiersMatchKey -> incorporatedEntityInformation.identifiersMatch.toString.contains(DetailsMatchedKey))
This is incorrect (oops) as the match status is being converted to a boolean. This is only required when returning the journey data to the calling service.

2022-04-27 09:11 UTC, woollett-r commented on app/uk/gov/hmrc/incorporatedentityidentificationfrontend/services/AuditService.scala
> +          "isMatch" -> identifiersMatchStatus,
As we define audit values for isMatch, VerificationStatus and RegisterApiStatus even if the source value is undefined I think it is better not to use a the "Block" approach for these fields. The only field that requires this approach is the CtUtr as this is optional for Registered Societies.

2022-04-27 11:14 UTC, robertom-binqua commented on app/uk/gov/hmrc/incorporatedentityidentificationfrontend/models/IncorporatedEntityInformation.scala
> +        Json.obj(IdentifiersMatchKey -> incorporatedEntityInformation.identifiersMatch.toString.contains(DetailsMatchedKey))
okay

2022-04-27 12:34 UTC, robertom-binqua commented on app/uk/gov/hmrc/incorporatedentityidentificationfrontend/services/CtEnrolmentService.scala
> +                  _ <- storageService.storeIdentifiersMatch(journeyId, DetailsMatched)
Perfect

2022-04-27 14:11 UTC, robertom-binqua approved these changes

2022-04-27 14:40 UTC, merged